name: Cron_Build

on: 
  schedule:
#             ┌───────────── minute (0 - 59)
#             │ ┌───────────── hour (0 - 23)
#             │ │ ┌───────────── day of the month (1 - 31)
#             │ │ │ ┌───────────── month (1 - 12 or JAN-DEC)
#             │ │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
#             │ │ │ │ │                                   
#             │ │ │ │ │
#             │ │ │ │ │
#             * * * * *
    - cron:  '0 */6 * * *'

jobs:
  run:
    name: Build with IDF ${{ matrix.idf_branch }}
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        idf_branch: [release/v3.3-solo1]
        #idf_branch: [release/v3.3, release/v4.0]
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: sudo apt-get install git wget curl libssl-dev libncurses-dev flex bison gperf python python-pip python-setuptools python-serial python-click python-cryptography python-future python-pyparsing python-pyelftools cmake ninja-build ccache
    - name: Install Python Wheel
      run: pip install wheel
    - name: Build
      env:
        GITHUB_TOKEN: ${{ secrets.PUSH_TOKEN }}
        IDF_BRANCH: ${{ matrix.idf_branch }}
      run: bash ./tools/cron.sh
    - name: Upload archive
      uses: actions/upload-artifact@v1
      with:
        name: esp32-arduino
        path: dist
    - uses: actions/download-artifact@v2
      with:
        name: esp32-arduino
        path: ./esp32-arduino
    - name: Display structure of downloaded files
      run: ls -R
      working-directory: ./esp32-arduino       
    - name: Commit files  # transfer the builded files back into the repository
      run: |
        git config --local user.name "esp32-arduino-lib-builder"
        git rm -r --cached .
        git add -f ./esp32-arduino/*.*
        git commit -m "esp32-arduino"
    - name: Push changes  # push the firmware files to branch esp32-arduino-lib-builder-IDF33-solo1
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: 'esp32-arduino-lib-builder-IDF33-solo1'
        force: true
