name: TASMOTA ESP32 Arduino Solo1

on:
  workflow_dispatch:  # Manually start a workflow
  push:
    branches:
    - tasmota/v3.3-solo1
  pull_request:

jobs:
  build-libs:
    name: Build Arduino Libs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8.10'
        architecture: 'x64' 
    - name: Install dependencies
      run: bash ./tools/prepare-ci.sh
    - name: Build Arduino Libs
      run: bash ./build.sh
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: esp32-arduino
        path: dist
    - name: Download new builded framework
      uses: actions/download-artifact@v2
      with:
        name: esp32-arduino
        path: ./esp32-arduino
    - name: Display files from folder esp32-arduino 
      run: ls esp32-arduino/*
    - name: Release
      uses: softprops/action-gh-release@v1
      #if: startsWith(github.ref, 'refs/tags/')
      with:
        tag_name: ${{ github.run_number }}
        prerelease: true
        files: esp32-arduino/tasmota*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
