name: ESP32 Arduino Libs CI

on:
  push:
    branches:
    - release/v3.3-solo1
  pull_request:

jobs:

  build-libs:
    name: Build Arduino Libs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: sudo apt-get install git wget curl libssl-dev libncurses-dev flex bison gperf python python-pip python-setuptools python-serial python-click python-cryptography python-future python-pyparsing python-pyelftools cmake ninja-build ccache
    - name: Install Python Wheel
      run: pip install wheel
    - name: Build Arduino Libs
      run: bash ./build.sh
    - name: Upload archive
      uses: actions/upload-artifact@v1
      with:
        name: esp32-arduino
        path: dist
    - uses: actions/download-artifact@v2
      with:
        name: esp32-arduino
        path: ./esp32-arduino
    - name: Display structure of downloaded files
      run: ls -R
      working-directory: ./esp32-arduino       
    - name: Commit files  # transfer the builded files back into the repository
      run: |
        git config --local user.name "esp32-arduino-lib-builder"
        git rm -r --cached .
        git add -f ./esp32-arduino/*.*
        git commit -m "esp32-arduino-lib idf 3.3-solo1"
    - name: Push changes  # push the files to branch esp32-arduino-lib-builder-IDF33-solo1
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: 'esp32-arduino-lib-builder-IDF33-solo1'
        force: true
